# Generated by Django 3.2.9 on 2021-12-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211221_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='personal',
            new_name='personal_website_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='whatsapp',
            new_name='whatsapp_number',
        ),
    ]
