# Generated by Django 3.2.9 on 2021-12-30 14:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Local', 'Local'), ('World', 'World'), ('Campus', 'Campus')], max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('datePosted', models.DateField(auto_now_add=True, verbose_name='dd mm yyyy')),
                ('header_image', models.ImageField(upload_to='media/blogs')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
