# Generated by Django 3.2.9 on 2021-12-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header_image',
            field=models.ImageField(upload_to='media/news'),
        ),
    ]
