# Generated by Django 3.2.9 on 2021-12-10 11:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_category', models.CharField(max_length=20)),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('blog_description', models.TextField(max_length=100)),
                ('blog_readTime', models.CharField(max_length=2)),
                ('blog_datePosted', models.DateField(auto_now_add=True, verbose_name='dd mm yyyy')),
                ('header_image', models.ImageField(upload_to='media/blogs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
