# Generated by Django 3.2.9 on 2021-12-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_Id',
            field=models.CharField(auto_created=True, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.CharField(max_length=100),
        ),
    ]
