# Generated by Django 3.2.9 on 2021-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211210_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_Id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
