# Generated by Django 3.2.9 on 2021-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(default=['coding', 'technology', 'science'], max_length=20),
        ),
    ]
