# Generated by Django 3.2.9 on 2021-12-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(default='coding', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_readTime',
            field=models.IntegerField(max_length=2),
        ),
    ]
